name: CD Reusable workflow

on:
  workflow_call:

  workflow_dispatch:

env:
  REPOS_TOKEN: ${{ secrets.MG_TOKEN }}
  GH_TOKEN: ${{ github.token }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:

    runs-on: ubuntu-22.04
    
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      # - name: Wait for approval
      #   uses: ORT-DevOps-2023S2G1/manual-approval@develop
      #   with:
      #     secret: ${{ secrets.GITHUB_TOKEN }}
      #     approvers: mgonzalezgallo
      #     issue-title: "Deploying on DEV environment"
      #     issue-body: "Please approve or deny the deployment"

      - name: Deploy on DEV environment
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 637483454218.dkr.ecr.us-east-1.amazonaws.com
          echo "${{ github.event.repository.name }}-td-dev"
          TASK_DEFINITION=$(aws ecs describe-task-definition —-task-definition olas —-region="us-east-1")
          echo $TASK_DEFINITION
          echo $TASK_DEFINITION | jq '.containerDefinitions[0].image='\"637483454218.dkr.ecr.us-east-1.amazonaws.com/aws-ecr-${{ env.REPO_NAME }}:${{ github.run_id }}\" \ > task-def.json
          #aws ecs register-task-definition —-family ${{ github.event.repository.name }}-td-dev —-region=”us-east-1" —-cli-input-json file://task-def.json
          #aws ecs update-service --cluster ort-cluster-dev --service ${{github.event.repository.name}}-dev --force-new-deployment
          #"${{ github.event.repository.name }}-td-dev"
          
      # - name: Wait for approval
      #   uses: ORT-DevOps-2023S2G1/manual-approval@develop
      #   with:
      #     secret: ${{ secrets.GITHUB_TOKEN }}
      #     approvers: mgonzalezgallo
      #     issue-title: "Deploying on STG environment"
      #     issue-body: "Please approve or deny the deployment"

      # - name: Deploy on STG environment
      #   run: aws ecs update-service --cluster ort-cluster-stg --service ${{github.event.repository.name}}-stg --force-new-deployment

      # - name: Wait for approval
      #   uses: ORT-DevOps-2023S2G1/manual-approval@develop
      #   with:
      #     secret: ${{ secrets.GITHUB_TOKEN }}
      #     approvers: mgonzalezgallo
      #     issue-title: "Deploying on PRD environment"
      #     issue-body: "Please approve or deny the deployment"
          
      # - name: Deploy on PRD environment
      #   run: |
          
      #     aws ecs update-service --cluster ort-cluster-prd --service ${{github.event.repository.name}}-prd --force-new-deployment


