name: CD Reusable workflow

on:
  workflow_call:

  workflow_dispatch:

env:
  REPOS_TOKEN: ${{ secrets.MG_TOKEN }}
  GH_TOKEN: ${{ github.token }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy_dev:

    runs-on: ubuntu-22.04
    
    name: Build Test and Release
    steps:
      - uses: actions/checkout@v4

      - name: chequeos
        run: echo "nada por ahora"
