name: Reusable workflow

on:
  workflow_call:

jobs:
  build_job:

    runs-on: ubuntu-22.04
    
    name: Build JAR
    steps:
      - uses: actions/checkout@v4

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Inspecting code with SonarCloud
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ORT-DevOps-2023S2G1_orders-service -Dsonar.login=7eaad0924bf3589d0b34001cae2f5185e7112d05

      - name: Building JAR and moving JAR to specific folder
        run: |
          mvn --batch-mode --update-snapshots verify
          mkdir staging && cp target/*.jar staging

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 2
        with:
          secret: ${{ github.TOKEN }}
          approvers: marcos
          minimum-approvals: 1

      #- name: Creating artifact with JAR file 
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Package
      #    path: staging
