name: CI Reusable workflow

on:
  workflow_call:

  workflow_dispatch:

env:
  REPOS_TOKEN: ${{ secrets.MG_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
  GH_TOKEN: ${{ github.token }}
  APP_ARGS: 'http://localhost:8081 http://localhost:8082 http://localhost:8083'

jobs:
  build_test_release_job:

    runs-on: ubuntu-22.04
    
    name: Build Test and Release
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Building with Maven and Inspecting code with SonarCloud
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.token=${{ env.SONAR_TOKEN }}  

      - name: Moving JAR to specific folder
        run: |
          mkdir staging && cp target/*.jar staging
          ls staging
          
      - name: Building environment
        if: ${{ github.repository }} == 'orders-service'
        run: | 
          java -jar staging/orders-service-example.jar ${{ env.APP_ARGS }} --server.port=8080
          gh repo clone ORT-DevOps-2023S2G1/payments-service
          cd payments-service
          mvn -B package
          java -jar payments-service-example.jar --server.port=8081
          cd -
          gh repo clone ORT-DevOps-2023S2G1/products-service
          cd products-service
          mvn -B package
          java -jar products-service-example.jar --server.port=8083
          cd -
          gh repo clone ORT-DevOps-2023S2G1/shipping-service
          cd shipping-service
          mvn -B package
          java -jar shipping-service-example.jar --server.port=8082

      # - name: Install Postman CLI
      #   run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # - name: Login to Postman CLI
      #   run:  postman login --with-api-key ${{ env.POSTMAN_API_KEY }}

      # - name: Get JSON file with postman collection
      #   run: |
      #     curl -H 'Authorization: token ${{ env.REPOS_TOKEN }}' \
      #     -H 'Accept: application/vnd.github.v4.raw' \
      #     -O \
      #     -L https://api.github.com/ORT-DevOps-2023S2G1/workflows-repository/DevOps-ApiCollection.postman_collection.json 
              
      # - name: Run API tests using Postman CLI
      #   run: postman collection run DevOps-ApiCollection.postman_collection.json

      # - name: Wait for approval
      #   uses: ORT-DevOps-2023S2G1/manual-approval@develop
      #   with:
      #     secret: ${{ secrets.GITHUB_TOKEN }}
      #     approvers: mgonzalezgallo
