name: CI Reusable workflow

on:
  workflow_call:

env:
  TOKEN: ${{ secrets.MG_TOKEN }}

jobs:
  build_test_release_job:

    runs-on: ubuntu-22.04
    
    name: Build Test and Release
    steps:
      - uses: actions/checkout@v4

     
      #- run: echo ${{ env.TOKEN }}
        
      #- uses: actions/setup-java@v3
      #  with:
      #    java-version: '17'
      #    distribution: 'temurin'
      
      - name: Inspecting code with SonarCloud
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ORT-DevOps-2023S2G1_orders-service -Dsonar.login=7eaad0924bf3589d0b34001cae2f5185e7112d05
          ls
          cd target
          ls

      #- name: Building JAR and moving JAR to specific folder
      #  run: |
      #    mvn --batch-mode --update-snapshots verify
      #    mkdir staging && cp target/*.jar staging

      # - name: Install Postman CLI
      #   run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # - name: Get JSON file with postman collection
      #   run: |
      #     curl -H 'Authorization: token ${{ env.TOKEN }}' \
      #     -H 'Accept: application/vnd.github.v4.raw' \
      #     -O \
      #     -L https://api.github.com/ORT-DevOps-2023S2G1/workflows-repository/DevOps-ApiCollection.postman_collection.json 
              
      # - name: Run API tests using Postman CLI
      #   run: postman collection run DevOps-ApiCollection.postman_collection.json

      #- name: Creating artifact with JAR file 
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Package
      #    path: staging

      #- name: Wait for approval
      #  uses: ORT-DevOps-2023S2G1/manual-approval@develop
      #  with:
      #    secret: ${{ secrets.GITHUB_TOKEN }}
      #    approvers: mgonzalezgallo, GonzaFernandez
