name: Reusable workflow

on:
  workflow_call:

jobs:
  build_job:

    runs-on: ubuntu-22.04
    
    name: Build JAR
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Building JAR and moving JAR to specific folder
        run: |
          mvn --batch-mode --update-snapshots verify
          mkdir staging && cp target/*.jar staging

      - name: Creating artifact with JAR file 
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
